"""
Django settings for p_decharlas project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

#Descripción: Este archivo contiene la configuración de la aplicación, como el nombre de la aplicación, la configuración
# de la base de datos, la configuración de la plantilla, la configuración de la aplicación, etc.

import os
from pathlib import Path

#base_dir es la ruta absoluta del directorio del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

#Secret key es una cadena aleatoria que se utiliza para proporcionar una capa adicional de seguridad para la aplicación web
SECRET_KEY = 'django-insecure-6@i*_ljj^ucu4b74@()r@2fc0y&txbmtyndd$0r39sk=t2n$pd'

#DEBUG es un valor booleano que indica si la aplicación web se ejecuta en modo de depuración o no.
DEBUG = True

#ALLOWED_HOSTS es una lista de cadenas que especifica los nombres de host que pueden servir la aplicación web.
ALLOWED_HOSTS = ['darobra.pythonanywhere.com', 'localhost', '127.0.0.1'] #Nombre de pythonanywhere

# lista que especifica los nombres de las aplicaciones Django habilitadas para esta
INSTALLED_APPS = [
    'decharlas',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#Lista que especifica el orden de los middleware que se ejecutan durante las solicitudes de la aplicación web.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#ROOT_URLCONF es una cadena que contiene el nombre de la configuración de la aplicación web.
ROOT_URLCONF = 'p_decharlas.urls'

# Lista que especifica el orden de los motores de plantillas que se utilizan para cargar las plantillas de la aplicación web.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION es una cadena que contiene el nombre de la aplicación WSGI de la aplicación web.
WSGI_APPLICATION = 'p_decharlas.wsgi.application'

#DATABASES es un diccionario que contiene la configuración de la base de datos de la aplicación web.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# lista que contiene la configuración de las validaciones de contraseña de la aplicación web.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'   #Código de idioma predeterminado para la aplicación web.

TIME_ZONE = 'UTC'   #Zona horaria predeterminada para la aplicación web.

USE_I18N = True     #Habilita la internacionalización para la aplicación web.

USE_L10N = True     #Habilita la localización para la aplicación web.

USE_TZ = True        #Habilita la zona horaria para la aplicación web.


#STATIC_URL es una cadena que contiene la URL de la carpeta estática de la aplicación web.
STATIC_URL = '/static/'
"""STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]"""

#DEFAULT_AUTO_FIELD es una cadena que contiene el nombre de la clase de campo automático predeterminada para la aplicación web.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

